name: adcio_analytics
description: collect logs for event analysis of ADCIO projects.
version: 0.1.5
homepage: https://github.com/corca-ai/adcio_analytics

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^9.0.2
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
