name: adcio_analytics
description: collect logs for event analysis of ADCIO projects.
version: 0.3.1
homepage: https://github.com/corca-ai/adcio_analytics

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  visibility_detector: ^0.4.0+2
  adcio_core: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
